# Generated by Django 5.2.4 on 2025-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0005_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscheck',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='newscheck',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
