# Generated by Django 5.2.4 on 2025-08-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0006_newscheck_category_newscheck_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscheck',
            name='category',
        ),
    ]
