# Generated by Django 5.2.4 on 2025-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0007_remove_newscheck_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscheck',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
