# Generated by Django 5.2.4 on 2025-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0008_newscheck_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscheck',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
