# Generated by Django 5.2.4 on 2025-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0010_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
