# Generated by Django 5.2.4 on 2025-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0012_customuser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscheck',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newscheck',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
