# Generated by Django 5.2.4 on 2025-09-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsapp', '0013_newscheck_email_sent_newscheck_email_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscheck',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='newscheck',
            name='email_to',
        ),
    ]
